services:
  # REST API Server
  - type: web
    name: pulsa-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/app.js
    envVars:
      - key: NODE_ENV
        value: production

  # Telegram Bot (Background Worker)
  - type: worker
    name: pulsa-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false